Rewrite and refactor all of pycoast to meet minimum modern standards
pytroll/pycoast pull request #63
Opened 2022-05-11 18:30 UTC by djhoese

This PR makes every change necessary to make pycoast pass basic formatting, linting, and complexity checks. To be sure of that I have enabled pre-commit.ci and added a pre-commit config that can be used by developers to ensure the quality of the code moving forward. I am almost done with the flake8 complexity issues and then there are a few bandit security issues I need to look into.

 - [ ] Closes #xxxx 
 - [ ] Tests added 
 - [ ] Tests passed 
 - [ ] Passes ``git diff origin/main **/*py | flake8 --diff`` 
 - [ ] Fully documented

2022-05-12 19:18 UTC, djhoese commented
This could still definitely use a lot more work, but I've reduce the complexity *a lot* for the entire `cw_base.py` module. Some of it still isn't pretty, but I think it requires considering changing the algorithm. The hard part for handling the grid lines was that the minor lines depend on what the major lines are and a couple other odd combinations of things. This made it hard to separate the code further.

@lobsiger CodeFactor is *finally* happy :wink:

2022-05-13 06:35 UTC, mraspaud requested changes
Ok, I got tired of writing the same comment over and over, I think black should be fixed to allow 120 characters and not split stuff randomly.

2022-05-13 06:35 UTC, mraspaud commented on docs/source/test.rst
> +    $ nosetests tests/
Are we still using nose?

2022-05-13 06:35 UTC, mraspaud commented on pycoast/cw_base.py
> +    ):
can this be put on one line?

2022-05-13 06:35 UTC, mraspaud commented on pycoast/cw_base.py
> +        )
Can this be put one line?

2022-05-13 06:35 UTC, mraspaud commented on pycoast/cw_base.py
> +    ):
Can this be put on one line?

2022-05-13 06:35 UTC, mraspaud commented on pycoast/cw_base.py
> +        )
Can this be put back on one line?

2022-05-13 06:35 UTC, mraspaud commented on pycoast/cw_base.py
> +        )
This fits in one line

2022-05-13 06:35 UTC, mraspaud commented on pycoast/cw_base.py
> +            )
This fits on one line

2022-05-13 06:35 UTC, mraspaud commented on pycoast/cw_base.py
> +    ):
This fits on one line

2022-05-13 06:35 UTC, mraspaud commented on pycoast/cw_base.py
> +        )
This fits on one line.

2022-05-13 06:35 UTC, mraspaud commented on pycoast/cw_base.py
> +        )
This should fit on one line

2022-05-13 06:35 UTC, mraspaud commented on pycoast/cw_base.py
> +            ]
This fits on one line with 120 characters

2022-05-13 06:35 UTC, mraspaud commented on pycoast/cw_base.py
> +        )
This should fit on one line

2022-05-13 06:35 UTC, mraspaud commented on pycoast/cw_base.py
> +        )
Fits on one line

2022-05-13 06:35 UTC, mraspaud commented on pycoast/cw_base.py
> +                    )
one line

2022-05-13 06:35 UTC, mraspaud commented on pycoast/cw_base.py
> +            db_name, tag, resolution, level, zero_pad, db_root_path=db_root_path
one line, right?

2022-05-13 06:35 UTC, mraspaud commented on pycoast/cw_base.py
> +            )
1 line

2022-05-13 06:35 UTC, mraspaud commented on pycoast/cw_base.py
> +            )
I think you get my point now, one line

2022-05-13 06:35 UTC, mraspaud commented on pycoast/cw_base.py
> +        )
guess what?

2022-05-13 06:35 UTC, mraspaud commented on pycoast/cw_base.py
> +                )
here too

2022-05-13 06:35 UTC, mraspaud commented on pycoast/cw_base.py
> +                )
too short to be split

2022-05-13 06:35 UTC, mraspaud commented on pycoast/cw_base.py
> +    )
seriously?

2022-05-13 06:35 UTC, mraspaud commented on pycoast/cw_base.py
> +            ):
This is badly split.

2022-05-13 06:35 UTC, mraspaud commented on pycoast/cw_base.py
> +            )
one line

2022-05-13 12:16 UTC, djhoese commented
Ok, your comments have been addressed. I mentioned pytest in the test document. I updated black from using its default 88 character line length to 120.

2022-05-13 12:33 UTC, mraspaud commented
> Ok, your comments have been addressed. I mentioned pytest in the test document. I updated black from using its default 88 character line length to 120.

Great, I can continue reviewing then :) Thanks!!!

2022-08-15 09:00 UTC, mraspaud approved these changes
LGTM. Mixing the refactoring with "blackification" didn't help either, maybe the next time we do this, we should do two separate PRs? But from what I can see, the tests didn't change in functionality, so I think we're good.

2022-08-15 13:39 UTC, djhoese commented
Yes, agreed. This started as a "add pre-commit" PR but to include all of the hooks I wanted it required rewriting most of the package. And yes, no behavior was intentionally changed. Merging now and then I could start working toward a config interface and automatically download the coastline files.

2022-08-15 13:39 UTC, merged

2022-08-19 11:44 UTC, lobsiger commented
@djhoese @mraspaud  now that this refactoring PR is merged, do we have a chance to see a Pycoast V. 1.6.0 anytime soon?

2022-08-19 15:43 UTC, djhoese commented
@lobsiger I'm currently finishing my recovery from COVID and will need to submit a final report for one of my projects next week *then* catch up on all my other work. After all that, yes I'd like to look into a release. However, I noticed in the newest pre-commit PR #64 that one of the tests is failing with the new versions of dependencies. This test wasn't failing when this PR last ran it's CI. Debugging this test failure is the first major hurdle to getting a new release out. If you have any free time to investigate it would be much appreciated. Just narrowing the problem down to what versions of what dependencies causes the failure would be **huge**.